name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Create private properties
        run: |
          echo "spring.datasource.url=$DB_URL" >> ./src/main/resources/application-private.properties
          echo "spring.datasource.username=$DB_USER" >> ./src/main/resources/application-private.properties
          echo "spring.datasource.password=$DB_PASSWORD" >> ./src/main/resources/application-private.properties

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew bootJar

      - name: Upload build file to artifact
        uses: actions/upload-artifact@v4
        with:
          name: wegri
          path: ./build/libs/*.jar

  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build file from artifact
        uses: actions/download-artifact@v4
        with:
          name: wegri

      - name: Copy build file to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./*.jar
          target: ./deploy
